image: cardihab/pipelines-node-aws:10-alpine-chrome
stepdefinitions:
  - npmtest: &npmtest
      name: Run npm install and execute tests
      caches:
          - node
      script:
        - npm ci
        - npm run lint
        # - npm run test-ci # run unit tests

pipelines:
  default:
    - step: *npmtest

  branches:
    master:
      # - step: *npmtest
      - step:
          name: Build the library
          script:
            - npm install
            - npm run build

